# Netlify Configuration
# Deployment settings for hikki-prototype Vue app + serverless API

[build]
  # Build command (runs Vite build)
  command = "npm run build"

  # Directory to publish (Vite outputs to dist/)
  publish = "dist"

  # Serverless functions directory
  functions = "netlify/functions"

[build.environment]
  # Node version for build and functions
  NODE_VERSION = "18"

  # Ignore .env.example in secrets scanning (it contains example values, not real secrets)
  SECRETS_SCAN_OMIT_PATHS = ".env.example"

# Redirect API calls to serverless functions (MUST come first)
# /api/generate -> /.netlify/functions/generate
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# SPA routing - serve index.html for all other routes
# This enables client-side routing for Vue app
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# CORS headers for API responses
[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type"

# Cache static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
